### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by isteves** [azizka/CoordinateCleaner#4]
Hey @azizka, do you have the Rmd version of the PDFs in the Tutorials folder?  I saw a few typos as I was reading through it, and I would be happy to help fix them if you have an Rmd (that way I can easily PR).  Moving them into a `vignettes` folder would also be helpful so that it's consistent with other R packages. http://r-pkgs.had.co.nz/vignettes.html

You'll have the rest of the review/comments from me by the end of the long weekend!  (We've got Monday off this week.)

rOpenSci review: https://github.com/ropensci/onboarding/issues/210

**Comment by azizka** [comment]
Hi @isteves , thanks!
The .Rmd files are in the tutorial folder now. Thanks for the suggestion to include them as proper vignettes, I'll do so, when I work through your report.
